# Generated by Django 5.1 on 2024-09-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="media",
            field=models.FloatField(null=True),
        ),
    ]
